/* eslint-disable react/function-component-definition -- these are folds IconSrc
   render functions (called by folds' Icon), not React components. */
// Fork-only. Overrides folds' `Icons` enum with lucide-react icons. Each icon
// returns a lucide <svg> sized to fill folds' Icon container (both viewBox
// 0 0 24 24), so it nests inside folds' sized <svg>. `filled` toggles fill as an
// active-state cue. folds' `Icon` and `IconSrc` contract are unchanged, so cinny's
// custom IconSrc icons keep working. Wired via the `folds` alias in
// vite.config.js -> src/folds/index.ts.
import React from 'react';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AtSign,
  Ban,
  Bell,
  BellDot,
  BellOff,
  BellRing,
  Bold,
  Bookmark,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Coffee,
  Compass,
  CornerUpLeft,
  CornerUpRight,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Flag,
  Forward,
  Funnel,
  Gamepad2,
  Globe,
  Hand,
  Hash,
  Heading1,
  Heading2,
  Heading3,
  HeadphoneOff,
  Headphones,
  Heart,
  Hexagon,
  History,
  House,
  Image,
  Inbox,
  Info,
  Italic,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  List,
  ListFilter,
  ListOrdered,
  Lock,
  Mail,
  MailPlus,
  MessageCircle,
  MessageCircleMore,
  MessageSquareDot,
  MessageSquarePlus,
  MessageSquareReply,
  MessagesSquare,
  Mic,
  MicOff,
  Minus,
  Monitor,
  OctagonX,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PhoneOff,
  Pin,
  Play,
  Plus,
  PlusCircle,
  Power,
  Quote,
  Reply,
  RotateCw,
  ScreenShare,
  Search,
  SendHorizonal,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  Smile,
  SmilePlus,
  SquareCode,
  Star,
  Sticker,
  Strikethrough,
  Sun,
  Terminal,
  Trash2,
  TriangleAlert,
  Type,
  Underline,
  User,
  UserPlus,
  Video,
  VideoOff,
  Volleyball,
  Volume2,
  VolumeX,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { IconName, IconSrc } from 'folds/dist/components/icon/Icons';

// Fork-only icon fill strategy. Lucide is a stroke-based line set with no solid
// variants, so a `filled` cue cannot be auto-derived. Only icons that look good
// as a solid silhouette get the fill treatment (`solid`); the rest render a
// crisp outline and ignore `filled` (`outline`). Add names to SOLID as you
// verify each one; defaults to outline so nothing renders as a blob.
// createElement (not JSX) keeps these off the react/function-component-definition
// rule, since these are folds render functions, not React components.
const SOLID = new Set<string>(['Star']);

const outline =
  (Comp: LucideIcon): IconSrc =>
  () =>
    React.createElement(Comp, {
      width: '100%',
      height: '100%',
      fill: 'none',
      stroke: 'currentColor',
    });

const solid =
  (Comp: LucideIcon): IconSrc =>
  (filled) =>
    React.createElement(Comp, {
      width: '100%',
      height: '100%',
      fill: filled ? 'currentColor' : 'none',
      stroke: filled ? 'none' : 'currentColor',
    });

// Picks `solid` for whitelisted names, `outline` otherwise.
const makeIcon = (name: IconName, Comp: LucideIcon): IconSrc =>
  SOLID.has(name) ? solid(Comp) : outline(Comp);

export const Icons: Record<IconName, IconSrc> = {
  Home: makeIcon('Home', House),
  User: makeIcon('User', User),
  UserPlus: makeIcon('UserPlus', UserPlus),
  Mail: makeIcon('Mail', Mail),
  MailPlus: makeIcon('MailPlus', MailPlus),
  Star: makeIcon('Star', Star),
  PlusCircle: makeIcon('PlusCircle', PlusCircle),
  Explore: makeIcon('Explore', Compass),
  Smile: makeIcon('Smile', Smile),
  SmilePlus: makeIcon('SmilePlus', SmilePlus),
  Leaf: makeIcon('Leaf', Leaf),
  Sticker: makeIcon('Sticker', Sticker),
  Delete: makeIcon('Delete', Trash2),
  Phone: makeIcon('Phone', Phone),
  PhoneDown: makeIcon('PhoneDown', PhoneOff),
  Headphone: makeIcon('Headphone', Headphones),
  HeadphoneMute: makeIcon('HeadphoneMute', HeadphoneOff),
  Send: makeIcon('Send', SendHorizonal),
  Bell: makeIcon('Bell', Bell),
  BellRing: makeIcon('BellRing', BellRing),
  BellPing: makeIcon('BellPing', BellDot),
  BellMute: makeIcon('BellMute', BellOff),
  Message: makeIcon('Message', MessageCircle),
  MessageUnread: makeIcon('MessageUnread', MessageCircleMore),
  Setting: makeIcon('Setting', Settings),
  Search: makeIcon('Search', Search),
  Heart: makeIcon('Heart', Heart),
  Play: makeIcon('Play', Play),
  Pause: makeIcon('Pause', Pause),
  Sun: makeIcon('Sun', Sun),
  Photo: makeIcon('Photo', Image),
  Lock: makeIcon('Lock', Lock),
  Vlc: makeIcon('Vlc', Gamepad2),
  Flag: makeIcon('Flag', Flag),
  Ball: makeIcon('Ball', Volleyball),
  Bulb: makeIcon('Bulb', Lightbulb),
  Terminal: makeIcon('Terminal', Terminal),
  Pencil: makeIcon('Pencil', Pencil),
  Info: makeIcon('Info', Info),
  Shield: makeIcon('Shield', Shield),
  ShieldLock: makeIcon('ShieldLock', ShieldOff),
  ShieldUser: makeIcon('ShieldUser', ShieldCheck),
  Cup: makeIcon('Cup', Coffee),
  Pin: makeIcon('Pin', Pin),
  VolumeHigh: makeIcon('VolumeHigh', Volume2),
  VolumeHighLock: makeIcon('VolumeHighLock', VolumeX),
  VolumeHighGlobe: makeIcon('VolumeHighGlobe', Volume2),
  VolumeMute: makeIcon('VolumeMute', VolumeX),
  File: makeIcon('File', File),
  Category: makeIcon('Category', LayoutGrid),
  Peace: makeIcon('Peace', Hand),
  Eye: makeIcon('Eye', Eye),
  EyeBlind: makeIcon('EyeBlind', EyeOff),
  Warning: makeIcon('Warning', TriangleAlert),
  Funnel: makeIcon('Funnel', Funnel),
  Bookmark: makeIcon('Bookmark', Bookmark),
  Inbox: makeIcon('Inbox', Inbox),
  Thread: makeIcon('Thread', MessagesSquare),
  ThreadPlus: makeIcon('ThreadPlus', MessageSquarePlus),
  ThreadUnread: makeIcon('ThreadUnread', MessageSquareDot),
  ThreadReply: makeIcon('ThreadReply', MessageSquareReply),
  Monitor: makeIcon('Monitor', Monitor),
  ScreenShare: makeIcon('ScreenShare', ScreenShare),
  Server: makeIcon('Server', Server),
  Prohibited: makeIcon('Prohibited', Ban),
  NoEntry: makeIcon('NoEntry', OctagonX),
  Mic: makeIcon('Mic', Mic),
  MicMute: makeIcon('MicMute', MicOff),
  VideoCamera: makeIcon('VideoCamera', Video),
  VideoCameraMute: makeIcon('VideoCameraMute', VideoOff),
  Hash: makeIcon('Hash', Hash),
  HashLock: makeIcon('HashLock', Hash),
  HashGlobe: makeIcon('HashGlobe', Hash),
  HashSearch: makeIcon('HashSearch', Hash),
  HashPlus: makeIcon('HashPlus', Hash),
  Space: makeIcon('Space', Hexagon),
  SpaceLock: makeIcon('SpaceLock', Hexagon),
  SpaceGlobe: makeIcon('SpaceGlobe', Hexagon),
  SpaceSearch: makeIcon('SpaceSearch', Hexagon),
  SpacePlus: makeIcon('SpacePlus', Hexagon),
  ChevronRight: makeIcon('ChevronRight', ChevronRight),
  ChevronLeft: makeIcon('ChevronLeft', ChevronLeft),
  ChevronTop: makeIcon('ChevronTop', ChevronUp),
  ChevronBottom: makeIcon('ChevronBottom', ChevronDown),
  Plus: makeIcon('Plus', Plus),
  Minus: makeIcon('Minus', Minus),
  Cross: makeIcon('Cross', X),
  VerticalDots: makeIcon('VerticalDots', EllipsisVertical),
  HorizontalDots: makeIcon('HorizontalDots', Ellipsis),
  Check: makeIcon('Check', Check),
  CheckTwice: makeIcon('CheckTwice', CheckCheck),
  Download: makeIcon('Download', Download),
  External: makeIcon('External', ExternalLink),
  Clock: makeIcon('Clock', Clock),
  RecentClock: makeIcon('RecentClock', History),
  Power: makeIcon('Power', Power),
  ReplyArrow: makeIcon('ReplyArrow', Reply),
  ArrowGoRight: makeIcon('ArrowGoRight', CornerUpRight),
  ArrowGoRightPlus: makeIcon('ArrowGoRightPlus', Forward),
  ArrowGoRightCross: makeIcon('ArrowGoRightCross', CornerUpRight),
  ArrowGoLeft: makeIcon('ArrowGoLeft', CornerUpLeft),
  Markdown: makeIcon('Markdown', SquareCode),
  Attachment: makeIcon('Attachment', Paperclip),
  Alphabet: makeIcon('Alphabet', Type),
  AlphabetUnderline: makeIcon('AlphabetUnderline', Type),
  Text: makeIcon('Text', Type),
  Heading1: makeIcon('Heading1', Heading1),
  Heading2: makeIcon('Heading2', Heading2),
  Heading3: makeIcon('Heading3', Heading3),
  Bold: makeIcon('Bold', Bold),
  Italic: makeIcon('Italic', Italic),
  Underline: makeIcon('Underline', Underline),
  Strike: makeIcon('Strike', Strikethrough),
  Link: makeIcon('Link', Link),
  Code: makeIcon('Code', Code),
  BlockCode: makeIcon('BlockCode', SquareCode),
  BlockQuote: makeIcon('BlockQuote', Quote),
  OrderList: makeIcon('OrderList', ListOrdered),
  UnorderList: makeIcon('UnorderList', List),
  Mention: makeIcon('Mention', AtSign),
  Filter: makeIcon('Filter', ListFilter),
  Sort: makeIcon('Sort', ArrowUpDown),
  ArrowUpDown: makeIcon('ArrowUpDown', ArrowUpDown),
  ArrowRight: makeIcon('ArrowRight', ArrowRight),
  ArrowLeft: makeIcon('ArrowLeft', ArrowLeft),
  ArrowTop: makeIcon('ArrowTop', ArrowUp),
  ArrowBottom: makeIcon('ArrowBottom', ArrowDown),
  ArrowDropRight: makeIcon('ArrowDropRight', ChevronRight),
  ArrowDropLeft: makeIcon('ArrowDropLeft', ChevronLeft),
  ArrowDropTop: makeIcon('ArrowDropTop', ChevronUp),
  ArrowDropBottom: makeIcon('ArrowDropBottom', ChevronDown),
  Reload: makeIcon('Reload', RotateCw),
  Globe: makeIcon('Globe', Globe),
};
